line-length = 88
target-version = "py311"

extend-exclude = [
  "Tolouene",
  "notebooks",
  "airflow_logs",
  "artifacts",
  "data/processed",
]

[lint.per-file-ignores]
"scripts/validate_dataset.py" = ["E402"]
